### ISSUE TITLE
ValueError in fixpoint_loop.fixpoint_iter

### ISSUE THREAD

**Issue by 1250326** [bunnech/jkonet#6]
Dear contributors,

While testing your code, I found that setting `settings.fploop: True` in `config_base_jko.yaml` will cause the error `ValueError: setting an array element with a sequence.` The error is triggered by lines 155 or 161 in `jkonet/models/fixpoint_loop.py.` I believe you have spotted this issue already before.

May I know if your team has any plans to fix this issue? The fix point loop function seems connected to the inner loop optimization in the JKONET algorithm in your paper. I am unsure how important it is to reproduce the result in the paper and how this will affect the model performance on my dataset.

Thank you very much in advance for your help.

Best,
Oscar

**Comment by bunnech** [comment]
Dear Oscar,

This is due to changes in JAX. This repository is not actively maintained anymore. In case you are interested in benchmarking your method against state-of-the-art methods, I would recommend using more recent methods, i.e., https://github.com/matteopariset/unbalanced_sb and https://github.com/IBM/aligned_diffusion_bridges.

Best,
Charlotte

**Comment by 1250326** [comment]
Dear Dr Charlotte,

Thank you for your prompt reply and recommendations, and I will explore these recent methods.

Yours sincerely,
Oscar
